# fly.toml app configuration file generated for backend-solitary-surf-7315 on 2025-10-01T12:17:17+05:45
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-solitary-surf-7315'
primary_region = 'bom'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'
  DEBUG = 'False'
  FLY_APP_NAME = 'backend-solitary-surf-7315'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
